file:
  path: C:\WTIM\File
spring:
  datasource:
    username: root
    password: ""
    filters: mergeStat,wall,logback
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxWait: 6000
    validationQuery: SELECT 'x'
    testOnBorrow: true
    testOnReturn: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    url: jdbc:mysql://localhost:3306/wtim?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
    
security:
  oauth2:
    client:
      client-id: client
      client-secret: client
      scope: read,write,xx
      auto-approve-scopes: '.*'
      access-token-uri: http://localhost:8000/oauth/token
      user-authorization-uri: http://localhost:8000/oauth/authorize
      authorized-grant-types: authorization_code,refresh_token,password
    resource:
      id: service-all
      user-info-uri: http://localhost:8000/user/principal/get
      prefer-token-info: false

