system:
  cache:
    enable: false
file:
  path: C:\WTIM\File
server:
  port: 8000
spring:
  application:
    name: service-all    # 项目名称尽量用小写
  profiles.active: dev
  jackson:
    serialization: 
      write-dates-as-timestamps: true
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  # 数据源名称
  datasource: datasource
  # mapper配置路径
  mapper-locations: classpath:/mapper/*.xml
  classpath: com.*.dao.*
  # entity的包
  typeAliasesPackage: com.github.willisaway.user.model
  # 全局配置
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  config: classpath:logback-all.xml
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000